### ISSUE TITLE
Time Consuming when handling bigger data set

### ISSUE THREAD

**Issue by TAsUjxnMIL** [homarques/ireos-extension#1]
Hello Henrique O. Marques, 

I am using your code for evaluating Isolation Forest's results. My dataset contains up to 180.000 lines with 4 features. I am trying to execute the java code and this does take too long. Do you have an idea to make the computation faster?

PS. Thank you very much for your work! 

I look forward to hearing from you!

**Comment by homarques** [comment]
Hi TAsUjxnMIL,

Yes, for large datasets, you should use the [approximate IREOS](https://github.com/homarques/ireos-extension#approximate-ireos)

**Comment by TAsUjxnMIL** [comment]
Thank you very much for your fast reply!

Is there an explanation why KNN is able to approximate IREOS? 

Have you ever executed the code on Google Colab or another cloud service? I tried to do that but I had some problems because it is not that easy to execute Java code on such clouds. 

Is there also Python Code available to compute IREOS?

**Comment by homarques** [comment]
Unfortunately, there is no python code available yet.
The explanation of the approximation you can find in the paper: https://dl.acm.org/doi/10.1145/3394053

**Comment by TAsUjxnMIL** [comment]
Okay thank you very much, is this an extended version of the paper: https://dl.acm.org/doi/10.1145/2791347.2791352 ? 

And what about such cloud services like Google Colab and Kaggle, did you ever tried to run the IREOS code on these with GPU usage?

**Comment by homarques** [comment]
Yes, it is an extension of our first paper. And No, I haven’t tried to run on cloud services and/or with GPU usage.

**Comment by TAsUjxnMIL** [comment]
Okay I understand. 
I executed the Main.java code with my dataset. For Approximate IREOS I get Nan. Is there any reason why this does not work? 
Besides, when choosing k=100 for the approximation I get the error: 
`Exception in thread "Thread-562" java.lang.ArrayIndexOutOfBoundsException`
Do you know a solution for this?

**Comment by homarques** [comment]
Hi, difficult to say what exactly is happening, but by the error, maybe you are using a value of k larger than the dataset. If it is not this, and you could not solve this issue, send me a link to your dataset, solutions and parameters, then I can replicate the error, and see if can find a way to solve it.

**Comment by TAsUjxnMIL** [comment]
I could not recreate the error again, so I think the problem is solved, thank you anyway!
