### ISSUE TITLE
IREOS very low for ground truth 

### ISSUE THREAD

**Issue by TAsUjxnMIL** [homarques/ireos-extension#2]
Hello Henrique O. Marques, 
I have executed the code with different solutions. The problem is that the ground truth solution list gets an IREOS value of 0.073. There are other solutions from anomaly detection techniques which get an higher value (0.45 - 0.5).
My question is if those solutions are good which have their IREOS value close the the IREOS value of the ground truth or still the solutions with the higher IREOS values? 

Thank you very much!

**Comment by homarques** [comment]
Hi, 
The higher the IREOS values, the better the solution. Always.
We performed an experiment evaluating the ground truth of the dataset, please, take a look at section 4.1.2 of the paper.

**Comment by TAsUjxnMIL** [comment]
Okay thank you I will look at this section.
