### ISSUE TITLE
IREOS approximation takes too long

### ISSUE THREAD

**Issue by TAsUjxnMIL** [homarques/ireos-extension#4]
Hello Henrique O. Marques,
I am currently trying to calculate the IREOS value for the results of a dataset with about 8300 rows. 
Executing this line `int[][] knn = Utils.knn(db, k);` does already take hours.
Do you have any solution for this? 

I'd be grateful, thank you very much!

**Comment by homarques** [comment]
Hi Sujan,

It is a good question, it is not supposed to take this long on a reasonably small dataset.
This line of code only computes the KNN using ELKI, which is N^2.
There are faster ways to compute the KNN, but it does not seem to be the issue.
If you can send me a link to your dataset in a way I can replicate this problem, I can take a look for you.
However, I am out of my office right now, so I will be able to take a look only after August 24th.

**Comment by TAsUjxnMIL** [comment]
Hello Marques, 
the data I use is in the following link https://nextcloud.dhbw-stuttgart.de/index.php/s/pifGm7kGe2zZ9tc.
I replaced the existing data path in the main.java with the file. This takes really long.

**Comment by TAsUjxnMIL** [comment]
I figured out that by using not all features the calculation is much faster. The line `int[][] knn = Utils.knn(db, k);` is not problematic anymore. The code takes too long in this line `List<IREOSSolution> evaluatedSolutionsApprox = ireos.evaluateSolutions(knn);`. 
Do the feature values need to be scaled to an interval from 0 to 1, would this make a difference?

**Comment by TAsUjxnMIL** [comment]
After scaling the feature values with the StandardScaler the code is executing within seconds. This seems to be the solution.
